// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "main.h"
#include "clsAppContext.h"
#include <FL/x.h>

static void cb_Test(Fl_Button*, clsAppContext* v) {
  v->cbTest();
}

static void cb_Close(Fl_Button*, clsAppContext* v) {
  v->cbClose();
}

static void cb_New(Fl_Button*, clsAppContext* v) {
  v->cbNew();
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  clsAppContext AppContext;
  Fl::scheme("gtk+");
  { Fl_Double_Window* o = new Fl_Double_Window(345, 135, "FLTK window");
    w = o; if (w) {/* empty */}
    o->user_data((void*)(&AppContext));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Input* o = new Fl_Input(15, 60, 150, 25, "Test:");
      o->user_data((void*)(&AppContext));
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      AppContext.RegisterWg("intx_test",o);
    } // Fl_Input* o
    { Fl_Button* o = new Fl_Button(15, 10, 100, 25, "Test");
      o->callback((Fl_Callback*)cb_Test, (void*)(&AppContext));
      AppContext.RegisterWg("btn_Test",o);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(235, 10, 100, 25, "Close");
      o->callback((Fl_Callback*)cb_Close, (void*)(&AppContext));
      AppContext.RegisterWg("btn_Close",o);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(230, 75, 100, 25, "New");
      o->callback((Fl_Callback*)cb_New, (void*)(&AppContext));
      AppContext.RegisterWg("btn_New",o);
    } // Fl_Button* o
    AppContext.Win(o);
    AppContext.init_windows();
    o->end();
  } // Fl_Double_Window* o
  w->icon((const void *)LoadIcon(fl_display, MAKEINTRESOURCE(501)));
  w->show(argc, argv);
  return Fl::run();
}
