// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "form1.h"
#include "clsForm1Context.h"

static void cb_FLTK(Fl_Double_Window*, clsForm1Context* v) {
  v->cbClose();
}

static void cb_Test(Fl_Button*, clsForm1Context* v) {
  v->PutInPostBox(1, "Main");
}

static void cb_Close(Fl_Button*, clsForm1Context* v) {
  v->cbClose();
}

Fl_Double_Window* winit_form1() {
  Fl_Double_Window* w;
  static clsForm1Context Form1Context;
  { Fl_Double_Window* o = new Fl_Double_Window(305, 135, "FLTK window");
    w = o; if (w) {/* empty */}
    o->callback((Fl_Callback*)cb_FLTK, (void*)(&Form1Context));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Input* o = new Fl_Input(145, 10, 150, 25, "Please enter value:");
      o->user_data((void*)(&Form1Context));
      Form1Context.RegisterWg("intx_test",o);
    } // Fl_Input* o
    { Fl_Button* o = new Fl_Button(10, 100, 100, 25, "Test");
      o->callback((Fl_Callback*)cb_Test, (void*)(&Form1Context));
      Form1Context.RegisterWg("btn_Test",o);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(195, 100, 100, 25, "Close");
      o->callback((Fl_Callback*)cb_Close, (void*)(&Form1Context));
      Form1Context.RegisterWg("btn_Close",o);
    } // Fl_Button* o
    Form1Context.Win(o);
    o->end();
  } // Fl_Double_Window* o
  return w;
}
